#!/usr/bin/env node
// scripts/_artifact-writer.mjs
//
// Writes the artifact tree. Local filesystem today; the same interface backs the
// R2 publish step, so the build step never knows or cares where its output lands.

import { mkdirSync, writeFileSync, existsSync, rmSync, statSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { gzipSync } from "node:zlib";
import { CACHE_CONTROL } from "../shared/artifacts.mjs";

export class ArtifactWriter {
  constructor(root, { quiet = false } = {}) {
    this.root = root;
    this.quiet = quiet;
    this.written = [];
    this.bytes = 0;
  }

  /** Gzip level 9: these files are written 4 times a year and read constantly. */
  write(path, obj) {
    const full = join(this.root, path);
    mkdirSync(dirname(full), { recursive: true });
    const json = JSON.stringify(obj);
    const body = path.endsWith(".gz") ? gzipSync(json, { level: 9 }) : Buffer.from(json);
    writeFileSync(full, body);
    this.written.push({ path, bytes: body.length, raw: json.length });
    this.bytes += body.length;
    if (!this.quiet && body.length > 512 * 1024) {
      console.log(`    large artifact ${path}: ${(body.length / 1024).toFixed(0)}KB gz`);
    }
    return body.length;
  }

  clear(subdir = "") {
    const target = join(this.root, subdir);
    if (existsSync(target)) rmSync(target, { recursive: true, force: true });
  }

  summary() {
    const raw = this.written.reduce((a, w) => a + w.raw, 0);
    return {
      files: this.written.length,
      gzBytes: this.bytes,
      rawBytes: raw,
      ratio: raw > 0 ? this.bytes / raw : 0,
      largest: [...this.written].sort((a, b) => b.bytes - a.bytes).slice(0, 5),
    };
  }
}

/**
 * Headers the serving layer must set.
 *
 * Immutable artifacts are cached for a year and busted by the `?b={buildId}`
 * query the manifest hands out; the manifest itself is the only file that
 * changes in place, so it gets a short cache. Getting this wrong in either
 * direction is expensive: too long on the manifest and a new quarter never
 * appears, too short on artifacts and every view re-downloads a fund's book.
 */
export function headersFor(path) {
  return path === "manifest.json"
    ? { "Cache-Control": CACHE_CONTROL.manifest, "Content-Type": "application/json" }
    : {
        "Cache-Control": CACHE_CONTROL.artifact,
        "Content-Type": "application/json",
        ...(path.endsWith(".gz") ? { "Content-Encoding": "gzip" } : {}),
      };
}

/** Emit a Cloudflare Pages `_headers` file matching the policy above. */
export function writeHeadersFile(root, dataPrefix = "/data") {
  const body = [
    "# Generated by scripts/_artifact-writer.mjs — do not edit by hand.",
    "",
    `${dataPrefix}/manifest.json`,
    `  Cache-Control: ${CACHE_CONTROL.manifest}`,
    "",
    "# Artifacts are immutable for a given build id; the manifest hands out",
    "# ?b={buildId} so a restated fund-quarter busts exactly one path and every",
    "# other file stays cached.",
    `${dataPrefix}/*`,
    `  Cache-Control: ${CACHE_CONTROL.artifact}`,
    "",
    "# Pre-gzipped at build time. Without this header the browser receives",
    "# gzip bytes and tries to parse them as JSON.",
    `${dataPrefix}/*.json.gz`,
    "  Content-Encoding: gzip",
    "  Content-Type: application/json",
    "",
  ].join("\n");
  mkdirSync(root, { recursive: true });
  writeFileSync(join(root, "_headers"), body);
}

export function dirSize(dir) {
  if (!existsSync(dir)) return { files: 0, bytes: 0 };
  let files = 0;
  let bytes = 0;
  const walk = (d) => {
    for (const e of readdirSync(d, { withFileTypes: true })) {
      const p = join(d, e.name);
      if (e.isDirectory()) walk(p);
      else {
        files++;
        bytes += statSync(p).size;
      }
    }
  };
  walk(dir);
  return { files, bytes };
}
