#!/usr/bin/env node
// scripts/_artifact-writer.mjs
//
// Writes the artifact tree. Local filesystem today; the same interface backs the
// R2 publish step, so the build step never knows or cares where its output lands.

import { mkdirSync, writeFileSync, existsSync, rmSync, statSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { createHash } from "node:crypto";
import { CACHE_CONTROL } from "../shared/artifacts.mjs";

export class ArtifactWriter {
  constructor(root, { quiet = false } = {}) {
    this.root = root;
    this.quiet = quiet;
    this.written = [];
    this.bytes = 0;
    /** path -> digest, for contentId(). */
    this.digests = new Map();
  }

  /**
   * Written as plain JSON. Compression is the CDN's job — see the note in
   * shared/artifacts.mjs. Pre-gzipping here produced double-encoded responses
   * behind Cloudflare and broke every widget.
   */
  write(path, obj) {
    const full = join(this.root, path);
    mkdirSync(dirname(full), { recursive: true });
    const json = JSON.stringify(obj);
    const body = Buffer.from(json);
    writeFileSync(full, body);
    this.digests.set(path, createHash("sha256").update(body).digest("hex"));
    this.written.push({ path, bytes: body.length, raw: json.length });
    this.bytes += body.length;
    if (!this.quiet && body.length > 512 * 1024) {
      console.log(`    large artifact ${path}: ${(body.length / 1024).toFixed(0)}KB`);
    }
    return body.length;
  }

  /**
   * A build id derived from what was BUILT, not from what was read.
   *
   * -------------------------------------------------------------------------
   * THE CACHE KEY MUST CHANGE WHEN THE CONTENT DOES
   * -------------------------------------------------------------------------
   * buildId was `buildIdFrom(latestAcceptance, windowSlug)` — a function of the
   * INPUT. Rebuilding the same windows therefore produced the same id, and since
   * artifacts are served `immutable, max-age=31536000` and busted only by the
   * `?b={buildId}` the manifest hands out, every returning visitor was served
   * whatever had been cached at that key a year earlier.
   *
   * Caught in production: a build ran after the 8,295-fund repair, the id went
   * BACKWARDS to a value used before it, and a fund whose R2 object correctly
   * held five quarters was served the four-quarter copy cached under the old id.
   * The data was right and the dashboard was wrong.
   *
   * Hashing the output keeps both properties: the same input still produces the
   * same tree and so the same id — which is what lets a rebuild be checked — but
   * any change in content, from any cause, produces a new one.
   *
   * Sorted before hashing, so write ORDER cannot change the id while the bytes
   * stay the same.
   */
  contentId() {
    const h = createHash("sha256");
    for (const path of [...this.digests.keys()].sort()) {
      h.update(path).update("\0").update(this.digests.get(path)).update("\n");
    }
    return h.digest("hex");
  }

  clear(subdir = "") {
    const target = join(this.root, subdir);
    if (existsSync(target)) rmSync(target, { recursive: true, force: true });
  }

  summary() {
    const raw = this.written.reduce((a, w) => a + w.raw, 0);
    return {
      files: this.written.length,
      gzBytes: this.bytes,
      rawBytes: raw,
      ratio: raw > 0 ? this.bytes / raw : 0,
      largest: [...this.written].sort((a, b) => b.bytes - a.bytes).slice(0, 5),
    };
  }
}

/**
 * Headers the serving layer must set.
 *
 * Immutable artifacts are cached for a year and busted by the `?b={buildId}`
 * query the manifest hands out; the manifest itself is the only file that
 * changes in place, so it gets a short cache. Getting this wrong in either
 * direction is expensive: too long on the manifest and a new quarter never
 * appears, too short on artifacts and every view re-downloads a fund's book.
 */
export function headersFor(path) {
  return path === "manifest.json"
    ? { "Cache-Control": CACHE_CONTROL.manifest, "Content-Type": "application/json" }
    : {
        "Cache-Control": CACHE_CONTROL.artifact,
        "Content-Type": "application/json",
        };
}

/** Emit a Cloudflare Pages `_headers` file matching the policy above. */
export function writeHeadersFile(root, dataPrefix = "/data") {
  // Rules MUST NOT overlap. Cloudflare Pages applies EVERY matching rule and
  // concatenates the values, so a `/data/*` immutable rule alongside a
  // `/data/manifest.json` rule produced
  //   "max-age=60, must-revalidate, public, max-age=31536000, immutable"
  // and made the one mutable file immutable — new builds would never reach a
  // returning visitor. Hence per-subdirectory rules that cannot match the
  // manifest.
  //
  // No Content-Encoding here: the CDN compresses in transit. Setting it caused
  // double-encoded responses. See shared/artifacts.mjs.
  const body = [
    "# Generated by scripts/_artifact-writer.mjs — do not edit by hand.",
    "",
    "# The only mutable file. Short cache so a new build becomes visible.",
    `${dataPrefix}/manifest.json`,
    `  Cache-Control: ${CACHE_CONTROL.manifest}`,
    "",
    "# Immutable for a given build id; the manifest hands out ?b={buildId} so a",
    "# restated fund-quarter busts exactly one path and everything else stays cached.",
    ...["meta", "period", "fund", "security"].flatMap((dir) => [
      `${dataPrefix}/${dir}/*`,
      `  Cache-Control: ${CACHE_CONTROL.artifact}`,
      "",
    ]),
  ].join("\n");
  mkdirSync(root, { recursive: true });
  writeFileSync(join(root, "_headers"), body);
}

export function dirSize(dir) {
  if (!existsSync(dir)) return { files: 0, bytes: 0 };
  let files = 0;
  let bytes = 0;
  const walk = (d) => {
    for (const e of readdirSync(d, { withFileTypes: true })) {
      const p = join(d, e.name);
      if (e.isDirectory()) walk(p);
      else {
        files++;
        bytes += statSync(p).size;
      }
    }
  };
  walk(dir);
  return { files, bytes };
}
